### ISSUE TITLE
None used classes generated in css output

### ISSUE THREAD

**Issue by rol4nd909** [frankstallone/astro-cube-boilerplate#4]
When instal and build the boilerplate there are classes generated that are not set in the html

I'n my example:
```css
.flex {
    display: flex
}

.transition {
    transition-property: color,background-color,border-color,text-decoration-color,fill,stroke,opacity,box-shadow,transform,filter,-webkit-backdrop-filter;
    transition-property: color,background-color,border-color,text-decoration-color,fill,stroke,opacity,box-shadow,transform,filter,backdrop-filter;
    transition-property: color,background-color,border-color,text-decoration-color,fill,stroke,opacity,box-shadow,transform,filter,backdrop-filter,-webkit-backdrop-filter;
    transition-timing-function: cubic-bezier(.4,0,.2,1);
    transition-duration: .15s
}
```

If you look at (https://github.com/rol4nd909/fm-accordion) then there are a lot more you can check in the browser here: 

[demo](https://rol4nd909.github.io/fm-accordion/)
